[package]
name = "proparm_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
egui_plot = "0.29.0"
serialport = "4.6.1"
